### ISSUE TITLE
预训练模型无法加载

### ISSUE THREAD

**Issue by zsw563545944** [Retinal-Research/EVIT-UNET#3]
你好，我在复现您代码的时候，在train_unetKD.py执行        pretrained_dict = torch.load(pretrained_path, map_location=device)
时出现了RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory的错误
![image](https://github.com/user-attachments/assets/2d8ebf9e-dcc9-4ec6-b3f4-23cea087f0f4)
，尝试过①重新下载文件以及②修改路径为绝对路径、③修改路径为./eformer_l_450.pth，都无法加载，希望能告知如何获得该预训练模型，如果您能检查一下该模型更好！期待回复
![20241113220309](https://github.com/user-attachments/assets/feadd12d-61a8-4a26-b8bb-89d38e0b398e)

**Comment by xenosxiny** [comment]
> 你好，我在复现您代码的时候，在train_unetKD.py执行 pretrained_dict = torch.load(pretrained_path, map_location=device) 时出现了RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory的错误 ![image](https://private-user-images.githubusercontent.com/58936534/385788506-2d8ebf9e-dcc9-4ec6-b3f4-23cea087f0f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNDc3OTUsIm5iZiI6MTczMjA0NzQ5NSwicGF0aCI6Ii81ODkzNjUzNC8zODU3ODg1MDYtMmQ4ZWJmOWUtZGNjOS00ZWM2LWIzZjQtMjNjZWEwODdmMGY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDIwMTgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1NTJlMjhmNTJhMDAxYWIzYTcwZTg3OGQ5M2FiYjM4OTM0OGZjZWI0Y2YyNDY4MTZlYmZlOTdhNzYzMDFkYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UKY6e1on6YYzXle9HPi7rNxKUhWctUV5tPXpapUQPuo) ，尝试过①重新下载文件以及②修改路径为绝对路径、③修改路径为./eformer_l_450.pth，都无法加载，希望能告知如何获得该预训练模型，如果您能检查一下该模型更好！期待回复 ![20241113220309](https://private-user-images.githubusercontent.com/58936534/385790023-feadd12d-61a8-4a26-b8bb-89d38e0b398e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNDc3OTUsIm5iZiI6MTczMjA0NzQ5NSwicGF0aCI6Ii81ODkzNjUzNC8zODU3OTAwMjMtZmVhZGQxMmQtNjFhOC00YTI2LWI4YmItODlkMzhlMGIzOThlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDIwMTgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzMTYzZmFmMjA1YThjMDBkN2JiZDgwZTI0ODJlMTE4OTc2ZjI3N2MxMmE4ZTI0N2RhOGQxMzUyYWRhYTc4MGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.j10eF4tx6qB90pPp-4xhjVp76qKiUxmC9R4LaAKvB2c)

您好, 之前的权重文件上传的时候损坏了  新的模型权重文件已经上传至google drive
