### ISSUE TITLE
readme文件有误

### ISSUE THREAD

**Issue by Kyochilian** [Retinal-Research/EVIT-UNET#6]
作者您好，感谢您的付出！
在'./datasets/readme.md'文件中，代码结构及作者邮箱是错误的。
![image](https://github.com/user-attachments/assets/d8a1f5f2-3827-492e-bcc9-7d59928b8d60)
该README文件中的代码结构为TransUNet的代码结构， 并没有找到"model"以及"data"文件夹。

**Comment by xenosxiny** [comment]
谢谢指正  训练过程只需要参考我们主目录下的md文件即可，修改root path，output dir等参数后，可以至今运行train_unetKD.py/test_unet.py文件。也可以直接从unet目录下找到我们的模型文件（eff_unet.py）直接使用。

**Comment by Kyochilian** [comment]
> 谢谢指正 训练过程只需要参考我们主目录下的md文件即可，修改root path，output dir等参数后，可以至今运行train_unetKD.py/test_unet.py文件。也可以直接从unet目录下找到我们的模型文件（eff_unet.py）直接使用。

好的，请问作者是否可以提供关于Synapse的数据集呢？
我使用了TransUNet作者提供的数据集，list与文件名均一致，但是它是灰度的，与论文中图像需输入的通道（channels=3）不一致。
我尝试将其扩充为三通道，或者从互联网上下载了三通道的数据集，但都显示Out Of memory，服务器显卡为A100，推测并不是显存不足的问题，应该为数据集不一致所致。
如果作者能提供论文所训的数据集就好了，再次感谢您的付出！
